version: '3'
services:
  web:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_USERNAME=root
      - DB_PASSWORD=Senha123
      - DB_DATABASE=meubanco

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
